apiVersion: v1
baseDomain: core.local
metadata:
  name: cl04

compute:
- hyperthreading: Disabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Disabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"0YwVA==","email":"georgiye@team.biz"},"quay.io":{"auth":"djfhsjkdfhkjs"},"registry.connect.redhat.com":{"auth":"09WT2xDQgdfgiz"},"registry.redhat.io":{"auth":"fHVoYyteam.biz"}}}'

sshKey: 'ssh-rsa AAAA'
